'
'
'
'	Autovideo command parser header
'	Autogenerated by mkcommand_h
'
'
'
Public Const  READ_IN_CELL = 			" "rdi" "
Public Const  READ_IN_REG = 			" "rai" "
Public Const  READ_OUT_CELL = 			" "rdo" "
Public Const  READ_OUT_REG = 			" "rao" "
Public Const  WRITE_OUT_CELL = 			" "wdo" "
Public Const  WRITE_IN_CELL = 			" "wdi" "
Public Const  WRITE_OUT_REG = 			" "wao" "
Public Const  WRITE_IN_REG = 			" "wai" "
Public Const  SET_DEBUG = 			" "debug" "
Public Const  SET_LOG = 			" "log" "
Public Const  BREAKPOINT = 			" "brk" "


